//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BloodStockTable
    {
        public int BloodStockID { get; set; }
        public int BloodGroupID { get; set; }
        public int BloodBankID { get; set; }
        public bool Status { get; set; }
        public int Quantity { get; set; }
        public System.DateTime BestBefore { get; set; }
    
        public virtual BloodBankTable BloodBankTable { get; set; }
        public virtual BloodGroupsTable BloodGroupsTable { get; set; }
    }
}
