//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonorTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonorTable()
        {
            this.RequestTables = new HashSet<RequestTable>();
            this.BloodStockDetailsTables = new HashSet<BloodStockDetailsTable>();
            this.RequestTables1 = new HashSet<RequestTable>();
        }
    
        public int DonorID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public int BloodGroupID { get; set; }
        public System.DateTime LastDonationDate { get; set; }
        public string ContactNumber { get; set; }
        public string CardNumber { get; set; }
        public string Address { get; set; }
        public int CityID { get; set; }
        public int UserID { get; set; }
        public int GenderID { get; set; }
    
        public virtual BloodGroupsTable BloodGroupsTable { get; set; }
        public virtual CityTable CityTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestTable> RequestTables { get; set; }
        public virtual UserTable UserTable { get; set; }
        public virtual GenderTable GenderTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BloodStockDetailsTable> BloodStockDetailsTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestTable> RequestTables1 { get; set; }
    }
}
